version: '3.12'

services:
  db:
    extends:
      file: common-services.yml
      service: db

  backend:
    extends:
      file: common-services.yml
      service: backend

  nginx:
    extends:
      file: common-services.yml
      service: nginx

volumes:
  static:
  media:
  db_data:
